insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (1, 'Kikelia', 'Burk', 'Massachusetts', true, 'M&A');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (2, 'Feodora', 'Shearston', 'Florida', false, 'Financial Management');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (3, 'Adriane', 'Dilland', 'Virginia', false, 'Software Engineering');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (4, 'Tabb', 'Blasl', 'New York', true, 'Law & Regulations');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (5, 'Genovera', 'Davis', 'Florida', false, 'Financial Management');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (6, 'Cathlene', 'Sarfass', 'Virginia', true, 'M&A');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (7, 'Shayla', 'Jowsey', 'California', true, 'Financial Management');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (8, 'Benyamin', 'Freeman', 'Louisiana', false, 'Software Engineering');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (9, 'Tomlin', 'Minot', 'Ohio', true, 'Analytics');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (10, 'Pierrette', 'Barneveld', 'California', false, '');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (11, 'Adolph', 'Blasetti', 'Kentucky', true, 'M&A');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (12, 'Amos', 'Braddick', 'New Mexico', true, 'Analytics');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (13, 'Franklin', 'Slaight', 'Florida', false, '');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (14, 'Jaquelin', 'Marushak', 'Maryland', true, 'Software Engineering');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (15, 'Brendon', 'Hallas', 'California', false, 'Data Science');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (16, 'Mireielle', 'Mote', 'California', false, 'M&A');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (17, 'Yankee', 'Kedie', 'Wisconsin', true, 'Analytics');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (18, 'Wyatan', 'Poulsum', 'Missouri', false, 'Accounting');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (19, 'Abbye', 'Murdie', 'Georgia', false, 'M&A');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (20, 'Myranda', 'Gilroy', 'New York', false, 'Law & Regulations');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (21, 'Regan', 'Prudence', 'West Virginia', true, '');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (22, 'Nataline', 'Gelder', 'Utah', true, 'Software Engineering');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (23, 'Kassia', 'Grumell', 'District of Columbia', false, 'Financial Management');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (24, 'Elisa', 'Birt', 'Alabama', false, 'Analytics');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (25, 'Tiena', 'Jollands', 'District of Columbia', false, 'Law & Regulations');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (26, 'Odie', 'Gaunt', 'Tennessee', true, 'Data Science');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (27, 'Aloise', 'Deedes', 'California', true, '');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (28, 'Meade', 'McCowan', 'Maryland', true, 'Data Science');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (29, 'Kanya', 'Morehall', 'Florida', true, '');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (30, 'Maura', 'Waddup', 'Michigan', true, 'Analytics');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (31, 'Eilis', 'Corps', 'California', true, '');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (32, 'Alethea', 'Knowlman', 'New York', true, 'Software Engineering');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (33, 'Jenda', 'Sikorski', 'New York', false, 'Analytics');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (34, 'Dana', 'Readett', 'Maryland', true, 'Financial Management');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (35, 'Alexis', 'Gronou', 'Texas', false, 'Law & Regulations');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (36, 'Euphemia', 'Charteris', 'Illinois', true, '');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (37, 'Collen', 'Boyd', 'Alabama', true, 'Software Engineering');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (38, 'Sonnie', 'Ganny', 'New York', true, 'Analytics');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (39, 'Florie', 'Cornfield', 'Texas', false, 'M&A');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (40, 'Silvain', 'Vaughn', 'Michigan', false, 'Accounting');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (41, 'Amby', 'Kneel', 'Idaho', false, 'Data Science');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (42, 'Ingemar', 'Ortet', 'Washington', true, '');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (43, 'Michel', 'Waith', 'Tennessee', true, 'Financial Management');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (44, 'Adler', 'Gian', 'Texas', false, 'Analytics');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (45, 'Andriana', 'Apark', 'Minnesota', true, 'Software Engineering');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (46, 'Boycey', 'Stower', 'Louisiana', false, 'Accounting');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (47, 'Ephraim', 'Trippick', 'New York', true, 'M&A');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (48, 'Cammi', 'Niave', 'Utah', false, 'Software Engineering');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (49, 'Pam', 'Wistance', 'Indiana', false, 'Data Science');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (50, 'Solly', 'Cadman', 'Nebraska', false, 'Analytics');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (51, 'Kathi', 'Zorener', 'Washington', true, 'Financial Management');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (52, 'Dorothee', 'Ahren', 'Michigan', true, 'Accounting');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (53, 'Jeannie', 'McDonand', 'Ohio', true, 'Data Science');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (54, 'Sawyer', 'Borham', 'California', false, 'Law & Regulations');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (55, 'Sigvard', 'Mallett', 'Florida', false, '');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (56, 'Bran', 'Dehm', 'California', true, 'Data Science');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (57, 'Jesselyn', 'Rosa', 'Utah', false, 'M&A');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (58, 'Mae', 'Dimmack', 'Indiana', false, 'M&A');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (59, 'Cherri', 'Willerson', 'Virginia', true, 'Analytics');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (60, 'Nani', 'Durran', 'Louisiana', true, 'Software Engineering');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (61, 'Dukie', 'Fishbie', 'Florida', true, 'Financial Management');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (62, 'Clyve', 'Ertel', 'Colorado', true, '');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (63, 'Rhodia', 'Blacktin', 'New York', false, 'Accounting');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (64, 'Jocelyn', 'Lantiff', 'Ohio', false, 'Law & Regulations');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (65, 'Libby', 'Dami', 'Texas', false, 'Law & Regulations');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (66, 'Pippa', 'Levey', 'Connecticut', false, 'Financial Management');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (67, 'Vernen', 'Maskell', 'North Carolina', false, '');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (68, 'Claude', 'Pillifant', 'Florida', true, 'M&A');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (69, 'Leena', 'Sturton', 'Pennsylvania', false, 'Software Engineering');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (70, 'Agustin', 'Rennicks', 'New York', false, 'Financial Management');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (71, 'Giorgi', 'Durn', 'California', false, 'M&A');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (72, 'Kacie', 'O''Crotty', 'Kentucky', true, 'Law & Regulations');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (73, 'Dinah', 'Caulcutt', 'Kansas', true, 'Financial Management');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (74, 'Bernie', 'Pennell', 'Florida', true, 'Accounting');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (75, 'Sampson', 'Marchent', 'Hawaii', false, '');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (76, 'Elizabeth', 'Mathie', 'Pennsylvania', false, '');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (77, 'Analiese', 'Hadigate', 'New York', true, 'Data Science');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (78, 'Forbes', 'Eltune', 'California', true, 'Accounting');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (79, 'Olenka', 'Bridges', 'California', false, 'Law & Regulations');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (80, 'Lura', 'Turgoose', 'Illinois', true, 'Data Science');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (81, 'Oriana', 'Tebbutt', 'North Carolina', false, 'Accounting');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (82, 'Revkah', 'Brendish', 'Illinois', false, 'Analytics');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (83, 'Della', 'Glencrosche', 'Ohio', true, 'Analytics');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (84, 'Hakim', 'MacLure', 'Texas', true, 'Data Science');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (85, 'Sadella', 'Overpool', 'Georgia', false, 'Accounting');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (86, 'Opalina', 'Kayser', 'South Carolina', false, '');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (87, 'Michele', 'Glasscott', 'Florida', false, 'Financial Management');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (88, 'Magdaia', 'Cornelis', 'West Virginia', false, '');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (89, 'Yancy', 'Blackler', 'Texas', true, '');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (90, 'Eirena', 'Magner', 'Texas', true, 'Financial Management');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (91, 'Moll', 'Dmytryk', 'Ohio', false, 'Accounting');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (92, 'Melita', 'Aylwin', 'Texas', true, 'Software Engineering');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (93, 'Moishe', 'Ferier', 'Texas', false, 'Law & Regulations');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (94, 'Elianora', 'McKintosh', 'Kansas', false, 'M&A');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (95, 'Kent', 'Banbrigge', 'Florida', true, 'Data Science');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (96, 'Dorthy', 'Mertsching', 'Missouri', true, 'M&A');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (97, 'Jorge', 'Ahlin', 'New Jersey', true, '');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (98, 'Bobbe', 'Ruperto', 'Utah', true, '');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (99, 'Sibylla', 'Bumfrey', 'District of Columbia', false, '');
insert into consultants (id, first_name, last_name, primary_location, willing_to_travel, area_of_expertise) values (100, 'See', 'Mollin', 'Indiana', false, 'Financial Management');
