insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (1, 'Georgie', 'Vardie', '16358 Anthes Place', null, 'Kansas City', 'Missouri', '64160');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (2, 'Jeramie', 'Youngs', '346 Moland Lane', null, 'Rockville', 'Maryland', '20851');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (3, 'Tiebold', 'Roby', '6031 Helena Junction', null, 'Jacksonville', 'Florida', '32277');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (4, 'Aldo', 'Fullstone', '3 Northland Center', null, 'Hot Springs National Park', 'Arkansas', '71914');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (5, 'Willy', 'Bonfield', '71 International Plaza', null, 'Des Moines', 'Iowa', '50305');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (6, 'Karol', 'Cantua', '819 Schlimgen Pass', null, 'Indianapolis', 'Indiana', '46231');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (7, 'Neall', 'Cullerne', '9713 South Alley', 924, 'Cleveland', 'Ohio', '44191');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (8, 'Annmaria', 'Abbate', '51 Hallows Center', null, 'Asheville', 'North Carolina', '28815');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (9, 'Bonnee', 'Larkcum', '7 Shelley Crossing', 718, 'Newport News', 'Virginia', '23612');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (10, 'Doralia', 'Boam', '203 Warner Way', null, 'Norfolk', 'Virginia', '23514');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (11, 'Shell', 'Haggarty', '04 Dryden Crossing', null, 'Sacramento', 'California', '94207');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (12, 'Aurelie', 'Densun', '997 Hagan Center', null, 'Bethesda', 'Maryland', '20816');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (13, 'Francoise', 'McCafferty', '76 Brentwood Crossing', 658, 'Cincinnati', 'Ohio', '45271');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (14, 'Frederich', 'Otley', '32 Meadow Valley Place', 266, 'Pensacola', 'Florida', '32505');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (15, 'Raquela', 'Monelli', '46 Eastlawn Pass', 134, 'Fairbanks', 'Alaska', '99709');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (16, 'Saunder', 'Joburn', '03554 Sutteridge Place', 788, 'Oklahoma City', 'Oklahoma', '73167');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (17, 'Israel', 'Minichi', '52 Northview Lane', 274, 'Salt Lake City', 'Utah', '84105');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (18, 'Elvin', 'Bruckent', '1 Blackbird Trail', 133, 'Chicago', 'Illinois', '60686');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (19, 'Tracy', 'Mawson', '2 Sunnyside Court', null, 'Laredo', 'Texas', '78044');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (20, 'Huntlee', 'Pethrick', '82 Valley Edge Center', 773, 'Southfield', 'Michigan', '48076');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (21, 'Ringo', 'Pedron', '37452 Walton Circle', 300, 'Tucson', 'Arizona', '85737');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (22, 'Karna', 'Feldhammer', '32 Schmedeman Point', null, 'Springfield', 'Illinois', '62794');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (23, 'Tarra', 'Cod', '52594 Del Sol Junction', 93, 'Honolulu', 'Hawaii', '96850');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (24, 'Belle', 'Lambirth', '4687 North Hill', null, 'Honolulu', 'Hawaii', '96825');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (25, 'Meryl', 'Vigours', '71 Nancy Crossing', 184, 'New York City', 'New York', '10280');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (26, 'Yehudit', 'Durnill', '05 Hoffman Plaza', 732, 'Springfield', 'Virginia', '22156');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (27, 'Skell', 'O''Suaird', '346 Scoville Place', null, 'Young America', 'Minnesota', '55557');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (28, 'Zolly', 'Althrop', '90 Springs Court', 701, 'Evansville', 'Indiana', '47712');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (29, 'Glynda', 'Berns', '59991 Hayes Pass', null, 'Baltimore', 'Maryland', '21290');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (30, 'Kimberley', 'Kuhnert', '4 Thierer Way', 576, 'Albuquerque', 'New Mexico', '87105');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (31, 'Troy', 'Klais', '90002 Ludington Pass', null, 'Shreveport', 'Louisiana', '71137');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (32, 'Sheffield', 'Soan', '8 Emmet Way', 391, 'Columbus', 'Ohio', '43231');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (33, 'Staffard', 'Brabin', '2 Northfield Crossing', null, 'Denver', 'Colorado', '80291');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (34, 'Janot', 'Dreigher', '554 Red Cloud Drive', 522, 'Gilbert', 'Arizona', '85297');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (35, 'Karon', 'Down', '126 Shopko Drive', 608, 'Dallas', 'Texas', '75277');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (36, 'Sisile', 'Symons', '43 Cascade Parkway', null, 'Omaha', 'Nebraska', '68179');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (37, 'Marcile', 'Doubrava', '9 Eggendart Circle', 728, 'Long Beach', 'California', '90805');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (38, 'Rouvin', 'Nicholes', '703 Anzinger Pass', 802, 'Racine', 'Wisconsin', '53405');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (39, 'Marti', 'Gillcrist', '2776 Wayridge Trail', 796, 'Washington', 'District of Columbia', '20046');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (40, 'Reamonn', 'Pickersail', '62 Pine View Point', null, 'Washington', 'District of Columbia', '20370');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (41, 'Sissy', 'Meaders', '63 Fairfield Avenue', 197, 'San Jose', 'California', '95173');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (42, 'Jacqui', 'Rigge', '39 Vidon Terrace', 345, 'Wichita', 'Kansas', '67260');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (43, 'Elizabet', 'Nozzolii', '7966 Morrow Way', null, 'Oklahoma City', 'Oklahoma', '73190');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (44, 'Gabriello', 'Padberry', '382 Lakewood Center', 387, 'Denton', 'Texas', '76205');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (45, 'Hermon', 'Brum', '7559 Jay Court', 886, 'Raleigh', 'North Carolina', '27658');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (46, 'Kalle', 'Norris', '52 Everett Point', 949, 'Baltimore', 'Maryland', '21281');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (47, 'Cicily', 'Kimmince', '8 Havey Point', 963, 'Denver', 'Colorado', '80243');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (48, 'Gorden', 'Risbridge', '411 Hooker Center', null, 'Washington', 'District of Columbia', '56944');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (49, 'Vite', 'Wardell', '315 Mallard Road', 580, 'Arlington', 'Virginia', '22244');
insert into customers (id, first_name, last_name, address1, address2, city, state, zip_code) values (50, 'Hulda', 'Liebrecht', '0 Hagan Road', 740, 'Shawnee Mission', 'Kansas', '66205');
