insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (1, 'Reichel, O''Connell and Will', 'Stationary', '4611 Summerview Drive', 640, 'Indianapolis', 'Indiana', '46216');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (2, 'Stehr, Pagac and Davis', 'Taxi & Limo', '3798 Sage Trail', null, 'Charlotte', 'North Carolina', '28278');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (3, 'Gulgowski-Goldner', 'Legal Services', '4 Kim Point', 536, 'Concord', 'California', '94522');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (4, 'Parker Group', 'Coworking Spaces', '85218 Westport Court', 150, 'Tucson', 'Arizona', '85748');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (5, 'Botsford, Shields and Fadel', 'Catering', '55 Valley Edge Plaza', null, 'Sioux City', 'Iowa', '51110');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (6, 'Kilback-Thompson', '', '962 Orin Parkway', 105, 'Springfield', 'Massachusetts', '01152');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (7, 'Aufderhar, Walker and Frami', '', '9 Pleasure Lane', null, 'Milwaukee', 'Wisconsin', '53215');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (8, 'Quitzon, Hermiston and Turner', 'Travel Agent', '2 Columbus Junction', 983, 'Escondido', 'California', '92030');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (9, 'Fritsch Inc', 'Real Estate', '051 Iowa Street', 704, 'El Paso', 'Texas', '79984');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (10, 'Koepp, Murazik and Emard', 'Stationary', '8 Main Way', 912, 'Memphis', 'Tennessee', '38114');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (11, 'Langworth LLC', 'Travel Agent', '7 Pankratz Center', 308, 'Lincoln', 'Nebraska', '68517');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (12, 'Cole, Klein and Sawayn', 'Travel Agent', '4067 Gina Place', 148, 'Fresno', 'California', '93726');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (13, 'Oberbrunner, Graham and Hessel', 'Taxi & Limo', '3 Lakewood Road', 933, 'Aurora', 'Colorado', '80045');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (14, 'Greenholt-Padberg', 'Coworking Spaces', '1342 Artisan Way', 301, 'Austin', 'Texas', '78703');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (15, 'Ziemann and Sons', 'Travel Agent', '84795 Onsgard Plaza', 629, 'Peoria', 'Illinois', '61629');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (16, 'Sipes, Farrell and O''Kon', 'Taxi & Limo', '67326 Bashford Terrace', null, 'San Antonio', 'Texas', '78278');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (17, 'Tremblay Inc', 'Coworking Spaces', '075 Pennsylvania Terrace', 504, 'Pittsburgh', 'Pennsylvania', '15235');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (18, 'King-MacGyver', 'Real Estate', '03175 Little Fleur Court', 992, 'Virginia Beach', 'Virginia', '23459');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (19, 'Adams-Renner', 'Editorial & Secretarial', '6 Fairfield Pass', 881, 'New York City', 'New York', '10045');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (20, 'Hansen, Goldner and Altenwerth', 'Real Estate', '842 Kipling Lane', null, 'Cheyenne', 'Wyoming', '82007');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (21, 'Veum LLC', 'Catering', '31361 Arapahoe Pass', 366, 'Evanston', 'Illinois', '60208');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (22, 'Renner, Schoen and Purdy', 'Travel Agent', '8 Fieldstone Drive', 950, 'San Diego', 'California', '92137');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (23, 'Rowe Group', 'Travel Agent', '96 Pine View Lane', 235, 'Denver', 'Colorado', '80241');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (24, 'Abernathy, Casper and Crist', 'Stationary', '8045 Merry Trail', 747, 'Wichita', 'Kansas', '67260');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (25, 'Block-Hilll', 'Travel Agent', '11 Dwight Place', 18, 'Houston', 'Texas', '77271');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (26, 'Torphy-Hilpert', 'Real Estate', '5257 Sommers Junction', 569, 'Gastonia', 'North Carolina', '28055');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (27, 'Koepp LLC', '', '2 Fulton Terrace', 371, 'Newton', 'Massachusetts', '02458');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (28, 'Larson-Maggio', 'Coworking Spaces', '4 Hagan Plaza', 883, 'Buffalo', 'New York', '14210');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (29, 'Schoen-Goyette', 'Real Estate', '27 Roth Street', null, 'Tulsa', 'Oklahoma', '74170');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (30, 'Friesen and Sons', '', '5721 Hoepker Plaza', 49, 'Oakland', 'California', '94605');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (31, 'Jacobi, Kirlin and Satterfield', 'Legal Services', '5 Hovde Pass', null, 'Los Angeles', 'California', '90055');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (32, 'Mosciski Group', 'Editorial & Secretarial', '69401 Arapahoe Alley', 265, 'Portland', 'Oregon', '97240');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (33, 'Marks-Reilly', 'Editorial & Secretarial', '9 Mockingbird Lane', 667, 'Tampa', 'Florida', '33610');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (34, 'Kessler-Parisian', 'Real Estate', '74742 Roth Circle', 146, 'Waterloo', 'Iowa', '50706');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (35, 'Moen-Nienow', 'Taxi & Limo', '23 Prentice Center', 379, 'Boston', 'Massachusetts', '02119');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (36, 'Sipes, Davis and Haley', 'Real Estate', '9141 Summerview Junction', null, 'Ann Arbor', 'Michigan', '48107');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (37, 'Gorczany-Upton', 'Real Estate', '42542 Monterey Hill', 356, 'Springfield', 'Illinois', '62776');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (38, 'Baumbach, Kuhn and Goodwin', 'Editorial & Secretarial', '0079 Declaration Alley', null, 'Lake Worth', 'Florida', '33462');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (39, 'Gusikowski, Smitham and Kohler', 'Editorial & Secretarial', '8383 Waubesa Center', null, 'Farmington', 'Michigan', '48335');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (40, 'Buckridge-Sipes', 'Stationary', '4178 Coleman Point', 235, 'Peoria', 'Illinois', '61614');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (41, 'Kuvalis-Collier', '', '97585 Northwestern Park', null, 'Las Vegas', 'Nevada', '89110');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (42, 'Welch-Wilkinson', 'Coworking Spaces', '4349 Stephen Way', null, 'Salt Lake City', 'Utah', '84140');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (43, 'McClure Group', '', '2 Sachs Pass', 655, 'New Castle', 'Pennsylvania', '16107');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (44, 'Herman, Cassin and Kunze', 'Taxi & Limo', '91069 Old Gate Junction', 334, 'New York City', 'New York', '10060');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (45, 'Bauch Group', '', '1628 Katie Pass', 505, 'Akron', 'Ohio', '44305');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (46, 'Reynolds-McCullough', 'Taxi & Limo', '6 Mendota Terrace', null, 'Iowa City', 'Iowa', '52245');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (47, 'Nikolaus-Hackett', '', '3 Drewry Pass', 273, 'Lansing', 'Michigan', '48912');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (48, 'Renner, Cremin and Lakin', 'Catering', '77 Hermina Pass', 534, 'Brockton', 'Massachusetts', '02405');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (49, 'Runolfsson Inc', 'Taxi & Limo', '51 La Follette Pass', null, 'Lexington', 'Kentucky', '40596');
insert into vendors (id, name, services, address1, address2, city, state, zip_code) values (50, 'Klein LLC', 'Coworking Spaces', '712 David Junction', 986, 'Buffalo', 'New York', '14210');
